### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by WilsonRCosta** [WilsonRCosta/ShiningCode-Clothes-Service#1]
- [ ] Authentication

- [ ] Product size type
- [ ] Stock available 
- [ ] Out of stock when not available
- [ ] Edit clothes quantity and size in shopping cart
- [ ] Develop _Modal_ on the adding to cart button in wishlist (set quantity and size)
